oclBlog.Web/Controllers/UdemyEducationController.cs
using ocLBlog.Data.Data;
using ocLBlog.Entities.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace oclBlog.Web.Controllers
{
    public class UdemyEducationController : Controller
    {
        ApplicationDbContext _db;

        public UdemyEducationController()
        {
            _db = new ApplicationDbContext();
        }

        [Route("~/ocl-udemy/udemy-online-lesson")]
        public ActionResult Index(int page = 1)
        {
            using (_db = new ApplicationDbContext())
            {
                var udemy = _db.Udemies.Where(i => i.IsDeleted == false).OrderByDescending(i => i.CreatedDate).ToPagedList(page, 15);
                return View(udemy);
            }
        }

        [Route("~/lessondetail/{newsTitle}-{id:int}")]
        public ActionResult Detail(int id, string seo_text)
        {
            Udemy udemyEducation = new Udemy();
            var eduDetail = _db.Udemies.Where(i => i.Id == id).FirstOrDefault();
            udemyEducation = eduDetail;
            return View(udemyEducation);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult yonas(int page = 1)
        {
            using (_db = new ApplicationDbContext())
            {
                var udemy = _db.Udemies.Where(i => i.IsDeleted == false).OrderByDescending(i => i.CreatedDate).ToPagedList(page, 15);
                return View(udemy);
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UdemyDetail(int id)
        {
            return View(_db.Udemies.Find(id));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Udemy model, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                image.SaveAs(Server.MapPath("~/img/udemy/" + image.FileName));
                model.Photo = image.FileName;
            }
            _db.Udemies.Add(model);
            _db.Entry(model).State = EntityState.Added;
            _db.SaveChanges();

            return RedirectToAction("yonas");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            using (_db=new ApplicationDbContext())
            {
                var udemyEdit = _db.Udemies.FirstOrDefault(i => i.Id == id);
                if (udemyEdit!=null)
                {
                    return View(udemyEdit);
                }
                return RedirectToAction("yonas");
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Udemy model, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                image.SaveAs(Server.MapPath("~/img/udemy/" + image.FileName));
                model.Photo = image.FileName;
            }
            _db.Udemies.Attach(model);
            _db.Entry(model).State = EntityState.Modified;
            _db.SaveChanges();

            return RedirectToAction("yonas");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            using (_db=new ApplicationDbContext())
            {
                var udemyDelete = _db.Udemies.Find(id);
                if (udemyDelete!=null)
                {
                    _db.Udemies.Remove(udemyDelete);
                    _db.SaveChanges();
                }
                return RedirectToAction("yonas");
            }
        }
    }
}

oclBlog.Web/Views/UdemyEducation/Create.cshtml
@model ocLBlog.Entities.Models.Udemy
@{
    ViewBag.Title = "Yeni Ders Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" enctype="multipart/form-data" action="">
                                    @using (Html.BeginForm("Create", "Udemy", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()                                       
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ders Başlığı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Title" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ders Altbaşlığı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Subtitle" type="text" required />
                                            </div>
                                        </div>
                                         <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ders Sayfa Linki</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="WebsiteLink" type="url" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="ccomment" class="control-label col-lg-2">Ders İçeriği</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control " id="ccomment" name="Detail"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="ccomment" class="control-label col-lg-2">Ders Açıklaması</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control " id="ccomment" name="Description"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Resim Ekle</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="image" type="file" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Ders Bilgilerini Ekle</button>
                                                <a href="~/Udemy/yonas"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

oclBlog.Web/Views/UdemyEducation/Detail.cshtml
@model ocLBlog.Entities.Models.Udemy
@{
    ViewBag.Title = "More Information of Online Lesson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="breadcumb-area black-opacity bg-img-7">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="breadcumb-wrap">
                    <h2>@ViewBag.Title</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="breadcumb-menu">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <ul>
                        <li><a href="~/Home/Index">Home</a></li>
                        <li>/</li>
                        <li><a href="~/ocl-udemy/udemy-online-lesson">Udemy Lessons</a></li>
                        <li>/</li>
                        <li>@ViewBag.Title</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="blog-details-area ptb-140">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="blog-details-wrap">
                    <div class="blog-details-img">
                        <img src="~/img/udemy/@Model.Photo" style="max-width:720px;max-height:376px;min-height:376px;min-width:720px" alt="@Model.Title">
                    </div>
                    <div class="blog-details-content">
                        <a href="@Model.WebsiteLink"><h3>@Model.Title</h3></a>
                        <blockquote>
                            @Model.Subtitle
                        </blockquote>
                        <p>@Model.Detail</p>
                        <p>@Model.Description</p>
                        <p>
                            <a href="@Model.WebsiteLink" class="btn btn-info" target="_blank">Analyze to Course</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="quote-area bg-1">
        <div class="container">
            <div class="row">
                <div class="col-sm-9 col-xs-12">
                    <div class="quote-wrap">
                        <h2>If you wanna ask something about this lessons you can visit while following to link you can ask me what do you want to ask.</h2>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12">
                    <div class="quote-wrap text-right">
                        <a href="~/contact/me">Request Quote</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

oclBlog.Web/Views/UdemyEducation/Edit.cshtml
@model ocLBlog.Entities.Models.Udemy
@{
    ViewBag.Title = "Ders Bilgilerini Güncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" enctype="multipart/form-data" action="">
                                    @using (Html.BeginForm("Create", "Udemy", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ders Başlığı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Title" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ders Altbaşlığı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Subtitle" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ders Sayfa Linki</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="WebsiteLink" type="url" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="ccomment" class="control-label col-lg-2">Ders İçeriği</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control " id="ccomment" name="Detail"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="ccomment" class="control-label col-lg-2">Ders Açıklaması</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control " id="ccomment" name="Description"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Resim Ekle</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="image" type="file" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Ders Bilgilerini Güncelle</button>
                                                <a href="~/Udemy/yonas"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

oclBlog.Web/Views/UdemyEducation/Index.cshtml
@using ocLBlog.Web.Toolkits
@using PagedList
@using PagedList.Mvc
@model IPagedList<ocLBlog.Entities.Models.Udemy>
@{
    ViewBag.Title = "My Online Education in Udemy.com";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="breadcumb-area black-opacity bg-img-7">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="breadcumb-wrap">
                    <h2>@ViewBag.Title</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="breadcumb-menu">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <ul>
                        <li><a href="~/Home/Index">Home</a></li>
                        <li>/</li>
                        <li>@ViewBag.Title</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="service-area ptb-100">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 col-sm-6 col-xs-12 col">
                    <div class="service-wrap mb-30">
                        <div class="service-img">
                            <img src="~/img/udemy/@item.Photo" style="max-height:303px;max-width:379px;min-height:303px;min-width:379px;" alt="@item.Title" />
                        </div>
                        <div class="service-content">
                            <h3>@item.Title</h3>
                            <p>@Html.Raw(HttpUtility.HtmlDecode(ocLBlog.Web.Toolkits.ReadMore.SafeSubstring(item.Subtitle, 80)))</p>
                            <a href="@Url.Action("Detail","UdemyEducation",new { newsTitle= @Url.SEOURLTitle(@item.Title), id=@item.Id })">Read More</a>
                        </div>
                    </div>
                </div>
            }
            <div class="col-xs-12">
                <div class="pagination-wrap">
                    @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
                </div>
            </div>
        </div>
    </div>
</section>

oclBlog.Web/Views/UdemyEducation/UdemyDetail.cshtml
@model ocLBlog.Entities.Models.Udemy
@{
    ViewBag.Title = "Udemy Eğitimi Detay Bilgisi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-10">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/UdemyEducation/yonas" class="btn btn-primary">Udemy Admin Sayfasına Dön</a> || <a href="~/UdemyEducation/Delete/@Model.Id" class="btn btn-danger">Ders Bilgilerini Sil</a>
                        </header>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Ders Detayı</th>
                                    <th>Ders Açılaması</th>
                                    <th>Ders Linki</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>@Model.Detail</td>
                                    <td>@Model.Description</td>
                                    <td><a href="@Model.WebsiteLink" class="btn btn-info" target="_blank">Website</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

oclBlog.Web/Views/UdemyEducation/yonas.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<ocLBlog.Entities.Models.Udemy>
@{
    ViewBag.Title = "Udemy Derslerim";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/UdemyEducation/Create"><button class="btn btn-primary">Yeni Udemy Dersi Ekle</button></a>
                        </header>
                        <table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th width="90">Resim</th>
                                    <th>Başlık</th>
                                    <th>Altbaşlık</th>
                                    <th>Eklenme Tarihi</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td width="90"><img src="~/img/udemy/@item.Photo" class="img-responsive" /></td>
                                        <td>@item.Title</td>
                                        <td>@item.Subtitle</td>
                                        <td>@item.CreatedDate.ToShortDateString()</td>
                                        <td>
                                        <td>
                                            <a href="~/UdemyEducation/UdemyDetail/@item.Id"><button class="btn btn-info btn-xs"><i class="icon-trash ">Detay</i></button></a>
                                            <a href="~/UdemyEducation/Edit/@item.Id"><button class="btn btn-success btn-xs"><i class="icon-trash ">Güncelle</i></button></a>                                           
                                            <a href="~/UdemyEducation/Delete/@item.Id"><button class="btn btn-danger btn-xs"><i class="icon-trash ">Sil</i></button></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
            <div class="pagination" align="center">
                <div class="pagination-large">
                    @Html.PagedListPager(Model, Page => Url.Action("yonas", new { Page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
                </div>
            </div>
        </section>
    </section>
</section>