oclBlog.Web/Controllers/LearnPriceController.cs
using Newtonsoft.Json;
using ocLBlog.Data.Data;
using ocLBlog.Entities.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static ocLBlog.Web.Controllers.CaptchaResult;

namespace ocLBlog.Web.Controllers
{
    public class LearnPriceController : Controller
    {
        public class CaptchaResult
        {
            public class CaptchaResponse
            {
                [JsonProperty("success")]
                public bool Success { get; set; }

                [JsonProperty("error-codes")]
                public List<string> ErrorCodes { get; set; }
            }
        }

        ApplicationDbContext _db;

        public LearnPriceController()
        {
            _db = new ApplicationDbContext();
        }

        [Route("~/price/orderproject")]
        public ActionResult Index()
        {
            using (_db = new ApplicationDbContext())
            {
                var price = _db.LearnPrices.Where(i => i.IsDeleted == false).ToList();
                return View();
            }
        }

        public ActionResult _Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _Create(LearnPrice model)
        {
            var response = Request["g-recaptcha-response"];
            const string secret = "6LcEEtkUAAAAAFbRjuk_4USKLu-7TmkEnVhavMci";

            var client = new WebClient();
            var reply =
                client.DownloadString(
                    string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secret, response));

            var captchaResponse = JsonConvert.DeserializeObject<CaptchaResponse>(reply);

            if (!captchaResponse.Success)
                TempData["Message"] = "Lütfen güvenliği doğrulayınız.";
            else
                TempData["Message"] = "Güvenlik başarıyla doğrulanmıştır.";

            if (ModelState.IsValid)
            {
                using (_db = new ApplicationDbContext())
                {
                    _db.LearnPrices.Add(model);
                    _db.Entry(model).State = EntityState.Added;
                    var result = _db.SaveChanges();

                    if (result > 0)
                    {
                        TempData["success"] = "İletiniz başarıyla gönderilmiştir.";
                    }
                    else
                    {
                        TempData["error"] = "İletiniz gönderilemedi. Lütfen kontrol ederek tekrar deneyiniz.";
                    }
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult yonas(int page = 1)
        {
            using (_db = new ApplicationDbContext())
            {
                var price = _db.LearnPrices.Where(i => i.IsDeleted == false).OrderByDescending(i => i.CreatedDate).ToPagedList(page, 10);
                return View(price);
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult LearnPriceDetail(int id)
        {
            return View(_db.LearnPrices.Find(id));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            using (_db = new ApplicationDbContext())
            {
                var deletePrice = _db.LearnPrices.Find(id);
                if (deletePrice != null)
                {
                    _db.LearnPrices.Remove(deletePrice);
                    _db.SaveChanges();
                }
                return RedirectToAction("yonas");
            }
        }
    }
}

oclBlog.Web/Views/LearnPrice/Index.cshtml
@model IEnumerable<ocLBlog.Entities.Models.LearnPrice>
@{
    ViewBag.Title = "Ask Your Project Price";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="breadcumb-area black-opacity bg-img-4">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="breadcumb-wrap">
                    <h2>@ViewBag.Title</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="breadcumb-menu">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <ul>
                        <li><a href="~/Home/Index">Home</a></li>
                        <li>/</li>
                        <li>Ask Price</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="contact-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <div class="contact-wrap form-style">
                    <h3>Ask Price for Your Website or Automation Project</h3>
                    <div class="cf-msg"></div>
                    @Html.Action("_Create", "LearnPrice")
                </div>
            </div>            
        </div>
    </div>
</div>

oclBlog.Web/Views/LearnPrice/LearnPriceDetail.cshtml
@model ocLBlog.Entities.Models.LearnPrice
@{
    ViewBag.Title = "Gelen Sipariş İsteği Detayı";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-10">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/LearnPrice/yonas" class="btn btn-primary">Sipariş Admin Sayfasına Dön</a> || <a href="~/LearnPrice/Delete/@Model.Id" class="btn btn-danger">Siparişi Sil</a>
                        </header>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Sitenin Türü</th>
                                    <th>Sitenin Özellikleri</th>
                                    <th>Kullanım Amacı</th>
                                    <th>Ek Diller</th>
                                    <th>Bitiş Zamanı</th>
                                    <th>Örnek</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>@Model.SiteKind</td>
                                    <td>@Model.SiteAttribute</td>
                                    <td>@Model.AreasOfUsage</td>
                                    <td>@Model.ChoiseLanguage</td>
                                    <td>@Model.FinishingTime.ToShortDateString()</td>
                                    <td>@Model.ForExpamle</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

oclBlog.Web/Views/LearnPrice/_Create.cshtml
@model ocLBlog.Entities.Models.LearnPrice
@{
    Layout = null;
}

@if (TempData["success"] != null)
{
    <div class="alert alert-success">
        <span>@TempData["success"]</span>
    </div>
}
else
{
    <div class="alert alert-success">
        <span>@TempData["error"]</span>
    </div>
}


@using (Html.BeginForm("_Create", "LearnPrice", FormMethod.Post))
{
    <form action="mail.php" method="post" id="cf">
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-xs-10">
                <input type="text" placeholder="Website Kind" id="fname" name="SiteKind">
            </div>
            <div class="col-xs-10">
                <textarea class="contact-textarea" placeholder="Site Attributes" id="msg" name="SiteAttribute"></textarea>
            </div>
            <div class="col-xs-10">
                <input type="text" placeholder="Website areas of use" id="email" name="AreasOfUsage">
            </div>
            <div class="col-xs-10">
                <input type="text" placeholder="website language" id="subject" name="ChoiseLanguage">
            </div>
            <div class="col-xs-10">
                <strong> Project Fisnishing Time</strong>
                <input type="date" id="subject" name="FinishingTime">
            </div>
            <div class="col-xs-10">
                <input type="text" placeholder="Sample Website" id="subject" name="ForExpamle">
            </div>
            <div class="col-xs-10">
                <input type="text" placeholder="Name-Surname" id="fname" name="YourNameSurname">
            </div>
            <div class="col-xs-10">
                <input type="text" placeholder="Phone Number" id="email" name="YourPhoneNumber">
            </div>
            <div class="col-xs-10">
                <input type="email" placeholder="MailAddress" id="subject" name="YourMailAddress">
            </div>
            <div class="col-xs-10">
                <input type="text" placeholder="City and Country" id="subject" name="YourCityandCountry">
            </div>
            <hr />
            <div class="col-xs-12">
                <div class="g-recaptcha" data-sitekey="6LcEEtkUAAAAAMulO9spSkNx0n4XS_YDFhyI4bEN"></div>
                <button id="submit" class="cont-submit btn-contact" name="submit">Send Form</button>
            </div>
        </div>
    </form>
}

oclBlog.Web/Views/LearnPrice/yonas.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<ocLBlog.Entities.Models.LearnPrice>
@{
    ViewBag.Title = "Gelen Fiyat Teklifleri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title ||
                        </header>
                        <table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th>Adı Soyadı</th>
                                    <th>Mail Adresi</th>
                                    <th>Telefon No:</th>
                                    <th>Şehir / Ülke</th>
                                    <th>Eklenme Tarihi</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.YourNameSurname</td>
                                        <td>@item.YourMailAddress</td>
                                        <td>@item.YourPhoneNumber</td>
                                        <td>@item.YourCityandCountry</td>
                                        <td>@item.CreatedDate.ToShortDateString()</td>
                                        <td>
                                            <a href="~/LearnPrice/LearnPriceDetail/@item.Id"><button class="btn btn-info btn-xs"><i class="icon-trash ">Detaya Bak</i></button></a>
                                            <a href="~/LearnPrice/Delete/@item.Id"><button class="btn btn-danger btn-xs"><i class="icon-trash ">Sil</i></button></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
            <div class="pagination" align="center">
                <div class="pagination-large">
                    @Html.PagedListPager(Model, Page => Url.Action("yonas", new { Page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
                </div>
            </div>
        </section>
    </section>
</section>